[package]
name = "fuzz-shrec"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
afl = "0.17.0"
arbitrary = { version = "1.4.2", features = ["derive"] }
foldhash = "0.2.0"
shrec = { version = "0.1.0", path = "../../crates/shrec", features = ["test"] }

[features]
trace = []
